/* Lógico_1: */
CREATE DATABASE IF NOT EXISTS base;

USE base;

CREATE TABLE MOTORISTA (
    cpf VARCHAR(14) PRIMARY KEY NOT NULL,
    nome VARCHAR(50) NOT NULL ,
    vencimentoDaCnh DATE NOT NULL,
    categoriaDaCnh VARCHAR(2) NOT NULL,
    pontos INT(3) NOT NULL,
    FK_VEICULO_placa VARCHAR(8)
);

CREATE TABLE VEICULO (
    placa VARCHAR(8) PRIMARY KEY NOT NULL, 
    marca VARCHAR(15) NOT NULL,
    modelo VARCHAR(15) NOT NULL,
    ano INT(4) NOT NULL,
    cor VARCHAR(10) NOT NULL,
    FK_MULTA_id INT(3)
);

CREATE TABLE MULTA (
    id INT(3) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    valor INT(10) NOT NULL,
    dataDaMulta DATE NOT NULL,
    pontos INT(2) NOT NULL,
    tipoDeInfracao VARCHAR(50) NOT NULL
);
 
ALTER TABLE MOTORISTA ADD CONSTRAINT FK_MOTORISTA_2
    FOREIGN KEY (FK_VEICULO_placa)
    REFERENCES VEICULO (placa)
    ON DELETE RESTRICT;
 
ALTER TABLE VEICULO ADD CONSTRAINT FK_VEICULO_2
    FOREIGN KEY (FK_MULTA_id)
    REFERENCES MULTA (id)
    ON DELETE RESTRICT;